// Canonical registry of per-domain EDITIONS - the copy and flourishes that
// differ between the production domains this one repo deploys to.
//
// "Edition" is the site's own existing word for a per-domain build, not a new
// coinage: src/_includes/excluded.njk has told readers "Not included in this
// edition" since narrowing was introduced. This file makes that concept
// first-class on the authoring side too.
//
// WHY THIS EXISTS, AND WHAT IT IS NOT
//
// Three mechanisms already vary a build per domain, and this is deliberately
// none of them:
//
//   - deploy.conf's CHARACTERS/TOPICS/THREADS (lib/content-filter.js) is
//     SUBTRACTIVE: it narrows an otherwise-full site down to a subset. It can
//     hide a page; it cannot give a domain a sentence of its own.
//   - THEME (src/css/theme-*.css, generated by scripts/generate-themes.js) is
//     COSMETIC: a palette swap, byte-identical to main.css otherwise.
//   - CUSTOM_LORE_FILE / CUSTOM_CSS_FILE (scripts/cpanel-deploy.sh) are
//     ADDITIVE but live OUTSIDE the repo, on the cPanel account. That is the
//     right shape for the case they were built for - content a third-party
//     clone operator owns, which Dermot cannot license into a CC BY-NC-ND
//     repo - and the wrong shape for his own per-domain copy, which wants to
//     be versioned, reviewable, checkable by `npm test` and the link/related
//     scripts, and inside the licence structure CONTENT-LICENSE.md describes.
//
// This registry is the fourth thing: additive, in-repo, per-domain copy.
//
// THE GOVERNING RULE: CANON IS CENTRALISED, VARIANTS ARE NON-CANONICAL
//
// Settled 2026-07-30, and it is a constraint on this file rather than a note
// about it. **Nothing an edition carries may assert a fact about the world.**
// Canon - src/seasons/, src/lore/, src/glossary/ - is identical on every
// domain, and every field here is framing: a tagline, which characters to put
// in a slideshow, which audio to offer. Reword the pitch, never the record.
//
// The test for a proposed field is not "is this nice for that domain?" but
// "could two domains now disagree about something true?" If yes, it does not
// belong here, and it does not belong anywhere else either.
//
// Note that this rule is what makes the multi-domain deployment coherent
// rather than merely convenient. Filtering can only ever SUBTRACT, so a
// narrowed clone shows a subset of one record and never a contradiction of it.
// If an edition could add lore, that guarantee would be gone: two domains
// could describe the same institution differently, and the archive would stop
// being a single record with several doors into it. That is also precisely why
// deploy.conf's CUSTOM_LORE_FILE is deprecated (2026-07-30) - injecting a page
// into src/lore/ per clone was the one mechanism that could produce
// per-domain canon. There is no replacement for it, on purpose.
//
// Two consequences worth stating, since both will come up:
//
//   - A domain that genuinely needs a page of its own gets a NON-canonical
//     one - an "about this edition" note, framing, front-of-house copy - not a
//     lore entry. If the material is worth being true, it is worth being true
//     everywhere, and it belongs in src/lore/ on every domain.
//   - The four canon statuses are unaffected and no fifth is being added.
//     An edition is not canon, not codex (which is in-universe authorship),
//     not an overlay (a declared reading of the same events), and not
//     chartered (another hand's work). It is the shop window, not the archive.
//
// WHY NOT KEEP USING `theme` FOR THIS
//
// Because `theme` was already doing it, and was already at its limit. The
// branches this file replaces were spelled `{% if theme == "fellowship" %}`,
// which conflates palette with identity and fails in three ways as domains
// diverge:
//
//   1. Several domains share one palette. sample-deploy.conf has four `fol*`
//      entries on THEME=fellowship and two `churchspace*` entries on
//      THEME=church-space - six domains, two identities. The moment one of
//      those four wants its own tagline, `theme` cannot express it.
//   2. A domain wanting a general-purpose palette (light, sepia,
//      high-contrast, solarized) plus its own copy had no way to ask: picking
//      the palette silently picked the copy too.
//   3. Copy organised by `theme` lives wherever the template is, so ONE
//      domain's identity scatters across src/index.md, base.njk and anything
//      added later. Edit points grow as domains x templates. This file
//      inverts that: one entry per edition, listing what that edition
//      overrides, however many templates read it.
//
// The two axes are now independent. `EDITION=folspace THEME=fellowship` is a
// sentence you can write.
//
// MIGRATION SAFETY - read before renaming an id
//
// getEdition() falls back to THEME when EDITION is unset, and every id below
// that names an existing look is spelled exactly as that theme is. deploy.conf
// is UNTRACKED and lives on the cPanel account, so the live configs cannot be
// updated from here - a live domain setting only THEME=fellowship therefore
// keeps rendering the fellowship edition with no edit at all. Renaming an id
// below, or dropping the THEME fallback, silently reverts those domains to the
// default copy. Add `EDITION=` to a deploy.conf first; retire the fallback
// only once every live clone sets it.
//
// ADDING AN EDITION
//
// Add an entry with an `id` and only the fields it actually overrides -
// editionFor() merges over DEFAULT_EDITION, so a domain that wants one new
// tagline writes one field, not a full record.
//
// `domains` IS LOAD-BEARING (since 2026-07-30). scripts/resolve-edition.js
// looks a domain up here so scripts/cpanel-deploy.sh can fill in THEME,
// THREADS, CHARACTERS, TOPICS, SITE_NAME, SITE_TITLE, COMMENTS_ENABLED and
// GISCUS_PROFILE for any key that clone's deploy.conf leaves unset - taking a
// minimum viable deploy.conf down to CPANEL_USER and DOMAIN.
//
// **deploy.conf still wins wherever it sets a value.** That is not only
// migration cover, it is the honest ordering: the values below for the alt
// domains are inferred from sample-deploy.conf's commented examples, since the
// real deploy.conf is untracked and cannot be read from here. The deploy log
// prints the provenance of every resolved key for exactly this reason - check
// it on the first deploy after this lands, and correct the entries below
// against what those domains actually set.
//
// WHY THIS DOES NOT WEAKEN PRIVATE-THREAD OPT-IN
//
// `threads` below can name `church-space`, a private thread, which
// lib/content-filter.js otherwise hides on every build. That is still explicit
// opt-in by naming, and naming it HERE is stronger than naming it in
// deploy.conf: this file is tracked, reviewed in a pull request, and versioned,
// where an untracked file on a cPanel account is none of those. What must never
// happen is opt-in inferred from the SHAPE of a domain string - "the host
// starts with church-space, so switch the thread on". That is pattern-matching
// masquerading as a decision. A registry entry is a decision.

const fs = require("fs");
const path = require("path");

// Every field an edition may override, with the values the unbranded
// full-site build (sciencefiction.site, GitHub Pages, local dev) uses.
// Anything absent from an edition below falls back to these.
const DEFAULT_EDITION = {
  id: "default",
  label: "Star Rangers (unbranded full site)",
  domains: ["sciencefiction.site", "dermot-r-cochran.github.io/star-rangers"],

  // ---- Deploy configuration, resolved by scripts/resolve-edition.js --------
  // Each of these maps to the deploy.conf key of the same name, upper-cased.
  // All are safe to hold here under the canon rule above: `theme` is a palette,
  // the three filters can only SUBTRACT from one shared record, and the rest
  // are branding or plumbing. None of them can make a domain assert a fact.

  // Palette name; "default" means src/css/main.css as-is.
  theme: "default",
  // Content narrowing. Empty = no narrowing (the full site). Arrays here,
  // joined to comma-separated strings for the env vars downstream.
  threads: [],
  characters: [],
  topics: [],
  // Branding. Empty = fall back to src/_data/site.js's own defaults.
  siteName: "",
  siteTitle: "",
  // giscus board selected by registered profile name (src/_data/giscus.js).
  // Empty = that file's built-in default profile. The raw GISCUS_*_ID values
  // deliberately do NOT live here: a profile name is meaningful only inside
  // this repo's registry, whereas the raw ids are what an independent host
  // supplies via their own giscus.local.json.
  giscusProfile: "",
  commentsEnabled: true,

  // ---- Copy and flourishes ------------------------------------------------
  // Homepage hero. `heroSubtitle` is trusted HTML - it carries inline links
  // and is rendered through Nunjucks' `safe`, so it is authored content and
  // must never be built from user input.
  heroSubtitle:
    'A station clock is forty seconds wrong, and it has stayed wrong for eleven years.\n    Star Rangers follows the people ordered to measure the drift, guard the public record, and decide what truth still survives across the Five Layers, the <a href="/star-rangers/lore/ensemble-multiverse/">Grand Ensemble Multiverse</a>, and multiple points of view.',

  // Character ids for the hero slideshow, resolved against the (filtered)
  // characters collection by the charactersByIds filter - so an id naming a
  // character this build excludes simply drops out of the slideshow rather
  // than breaking it.
  heroCharacterIds: ["aldera", "iona", "elvira", "galahad", "rook", "syra"],

  // Footer audio player. `file` is a filename in src/audio/.
  themeAudio: { label: "Celtic ambient", file: "celtic-theme.wav" }
};

const EDITIONS = [
  {
    id: "fellowship",
    label: "Fellowship of Light",
    domains: ["fellowshipoflight.org", "fol.org", "folonline", "folspace"],
    theme: "fellowship",
    // Inferred from sample-deploy.conf, where all four fol* examples pair
    // THEME=fellowship with THREADS=church-space. Confirm against the live
    // deploy.conf before trusting it - see the note at the top of this file.
    threads: ["church-space"],
    giscusProfile: "church-space",
    heroSubtitle:
      'A station clock is forty seconds wrong, and it has stayed wrong for eleven years. Long before any charter named them Rangers, an older order kept vigil at boundaries like this one. Star Rangers follows the people who inherited that watch — measuring the drift, guarding the public record, and deciding what light still survives across the Five Layers, multiple <a href="/star-rangers/glossary/concordant/">Concordants</a>, and multiple points of view.',
    themeAudio: { label: "Orchestral fantasy", file: "fellowship-theme.wav" }
  },
  {
    id: "starquest",
    label: "StarQuest",
    domains: ["starquest.site", "starquest.online"],
    theme: "starquest",
    heroSubtitle:
      'Forty seconds of drift. Eleven years unexplained. At the edge of the known, that\'s not a rounding error — it\'s a warning. Star Rangers follows the crews sent to chase it down: measuring the boundary, guarding the record, and racing to decide what\'s true before the Five Layers, the <a href="/star-rangers/glossary/concordant/">Concordants</a>, and every conflicting witness bury the answer for good.',
    themeAudio: { label: "Sci-fi ambient", file: "starquest-theme.wav" }
  },
  {
    id: "pets",
    label: "Undercover Pets",
    domains: ["undercover-pets.com"],
    theme: "pets",
    heroSubtitle:
      'A station clock is forty seconds wrong, and it has stayed wrong for eleven years — a small enough error that everyone assumed someone else was watching it. Star Rangers follows the people who finally did: measuring the drift, guarding the public record, and working out what truth still holds across the Five Layers, multiple <a href="/star-rangers/glossary/concordant/">Concordants</a>, and multiple points of view.',
    // The one existing edition that recasts the hero slideshow rather than
    // only rewording around it.
    heroCharacterIds: ["barsik", "bubochka", "eden-warden", "nessa", "rasa-oyelaran"],
    themeAudio: { label: "Playful ukulele", file: "pets-theme.wav" }
  },
  {
    // No COPY overrides on purpose - these domains diverge through the private
    // thread and their palette rather than through reworded front-of-house
    // text. Naming the edition anyway means the first flourish is a one-line
    // edit here rather than a new template branch.
    id: "church-space",
    label: "Church Space",
    domains: ["church-space.site", "church-space.online"],
    theme: "church-space",
    // The opt-in that makes these domains what they are. See the
    // private-thread note at the top of this file: naming it in a tracked,
    // reviewed registry is a stronger form of opt-in than naming it in an
    // untracked file on a server, not a weaker one.
    threads: ["church-space"],
    giscusProfile: "church-space"
  }
];

// An untracked, gitignored editions.local.json in the repo root, for anyone
// hosting this site independently. Exactly the pattern giscus.local.json
// already establishes (see src/_data/giscus.js), and for the same reason:
// registering your own domain should not require editing a tracked engine file,
// because that means maintaining a fork and re-resolving a conflict on every
// upstream merge. Template: sample-editions.local.json.
//
// Shape: { "editions": [ { "id": "...", "domains": [...], ...overrides } ] }
//
// An entry whose id matches one below OVERRIDES it (merged over, field by
// field); a new id is added. So an independent host can either re-point an
// existing edition at their own domain or declare their own outright.
//
// The canon rule still binds a local file completely - there is no field here
// that can add lore, and that is deliberate. It means an independent host
// cannot publish their own material as this story's canon even by accident,
// which protects them as much as it protects the record.
const LOCAL_CONFIG_PATH = path.join(__dirname, "..", "editions.local.json");

let localCache; // undefined = not yet read, null = absent

function loadLocalEditions() {
  if (localCache !== undefined) return localCache;

  let raw;
  try {
    raw = fs.readFileSync(LOCAL_CONFIG_PATH, "utf8");
  } catch (err) {
    if (err.code === "ENOENT") { localCache = null; return localCache; }
    throw err;
  }

  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    throw new Error(`lib/editions.js: editions.local.json is not valid JSON - ${err.message}`);
  }
  const list = parsed && parsed.editions;
  if (!Array.isArray(list)) {
    throw new Error(
      "lib/editions.js: editions.local.json must be { \"editions\": [ ... ] }. " +
      "See sample-editions.local.json for the expected shape."
    );
  }
  for (const e of list) {
    if (!e || typeof e.id !== "string" || !e.id.trim()) {
      throw new Error("lib/editions.js: every entry in editions.local.json needs a non-empty string `id`.");
    }
  }
  localCache = list;
  return localCache;
}

/**
 * The tracked registry with any editions.local.json entries merged in.
 * @returns {object[]} edition records (not yet merged over DEFAULT_EDITION)
 */
function allEditions() {
  const local = loadLocalEditions();
  if (!local || !local.length) return EDITIONS;

  const byId = new Map(EDITIONS.map((e) => [e.id, e]));
  for (const entry of local) {
    const id = entry.id.trim().toLowerCase();
    byId.set(id, { ...(byId.get(id) || {}), ...entry, id });
  }
  return [...byId.values()];
}

/**
 * Merge an edition over DEFAULT_EDITION so callers always get a complete
 * record and an entry only has to declare what it changes. Shallow by design:
 * `themeAudio` is replaced wholesale rather than merged key-by-key, because a
 * half-overridden audio player (new label, old file) is never what anyone
 * means.
 *
 * @param {string} id
 * @returns {object} complete edition record; DEFAULT_EDITION for an unknown id
 */
function editionFor(id) {
  const wanted = String(id || "").trim().toLowerCase();
  const found = allEditions().find((e) => e.id === wanted);
  return found ? { ...DEFAULT_EDITION, ...found } : { ...DEFAULT_EDITION };
}

/**
 * Look an edition up by the domain it serves.
 *
 * Matching is on the bare host, case-insensitively, with any scheme, `www.`,
 * port, path and trailing slash stripped first - so "https://Church-Space.site/"
 * and "church-space.site" are the same domain. A path-bearing entry (the
 * GitHub Pages one, "dermot-r-cochran.github.io/star-rangers") is matched on
 * its host part too, since a host cannot serve two editions.
 *
 * Returns null rather than DEFAULT_EDITION on no match, so a caller can tell
 * "this domain is registered as the default edition" apart from "this domain is
 * not registered at all" - the deploy log says which, and a silent default is
 * how a domain ends up quietly serving the wrong thing.
 *
 * @param {string} domain
 * @returns {object|null} complete edition record, or null if unregistered
 */
function editionForDomain(domain) {
  const host = bareHost(domain);
  if (!host) return null;
  const all = [DEFAULT_EDITION, ...allEditions()];
  const found = all.find((e) => (e.domains || []).some((d) => bareHost(d) === host));
  return found ? { ...DEFAULT_EDITION, ...found } : null;
}

function bareHost(value) {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/^[a-z]+:\/\//, "")
    .replace(/^www\./, "")
    .split("/")[0]
    .split(":")[0];
}

/**
 * Resolve the edition for this build from the environment.
 *
 * EDITION wins; THEME is the migration fallback (see MIGRATION SAFETY above);
 * an unset or unrecognised value yields DEFAULT_EDITION. Deliberately does NOT
 * throw on an unknown id, unlike GISCUS_PROFILE in src/_data/giscus.js - a
 * wrong giscus profile silently attaches reader comments to the wrong repo,
 * which is unrecoverable, whereas a wrong edition id costs a domain its
 * tagline and is obvious on the homepage.
 *
 * @returns {object} complete edition record
 */
function getEdition() {
  return editionFor(process.env.EDITION || process.env.THEME);
}

/**
 * Fail the build on a malformed registry. Called from .eleventy.js at config
 * time, so a mistake here stops the build instead of shipping a broken page.
 *
 * This exists because moving copy out of src/ cost some automatic checking,
 * and the loss should be paid back rather than absorbed. Two specifics:
 *
 *   - `themeAudio.file` used to appear in base.njk as a literal audio src
 *     under /star-rangers/audio/, which scripts/check-internal-links.js
 *     verified. It is now a bare filename assembled by a template, so that
 *     script skips it as a templated href - a typo would ship a player
 *     pointing at nothing. Checked against src/audio/ here instead.
 *     (Deliberately described rather than quoted as a path: that script now
 *     scans this file, and a made-up example URL in a comment would fail it -
 *     as one did while this was being written.)
 *   - `heroSubtitle` links ARE still covered: check-internal-links.js now
 *     scans this file by name (see its EXTRA_FILES).
 *
 * Duplicate ids are checked too: EDITIONS_BY_ID would silently keep the last
 * one, the same quiet-wrong-answer failure validate-content.js guards against
 * for chapter comment_id collisions.
 *
 * @param {string} audioDir absolute path to the directory holding audio files
 * @throws {Error} on a duplicate id, or an audio file that isn't there
 */
function validateEditions({ audioDir, cssDir }) {
  const all = [DEFAULT_EDITION, ...allEditions()];

  const seenIds = new Set();
  for (const e of all) {
    if (seenIds.has(e.id)) {
      throw new Error(`lib/editions.js: duplicate edition id "${e.id}" - only one of them would ever be used.`);
    }
    seenIds.add(e.id);
  }

  // A domain claimed by two editions is the worst failure mode this file has:
  // resolution would pick whichever came first and the other domain would
  // quietly serve the wrong branding forever. Cheap to rule out here.
  const seenDomains = new Map();
  for (const e of all) {
    for (const d of e.domains || []) {
      const host = bareHost(d);
      if (seenDomains.has(host)) {
        throw new Error(
          `lib/editions.js: domain "${host}" is claimed by both "${seenDomains.get(host)}" and "${e.id}".`
        );
      }
      seenDomains.set(host, e.id);
    }
  }

  for (const e of all) {
    const file = (e.themeAudio || DEFAULT_EDITION.themeAudio).file;
    if (!fs.existsSync(path.join(audioDir, file))) {
      throw new Error(
        `lib/editions.js: edition "${e.id}" names themeAudio.file "${file}", which is not in ${audioDir}.`
      );
    }
    // A typo'd theme name is not otherwise loud: cpanel-deploy.sh checks the
    // file exists and silently keeps main.css when it doesn't, so the domain
    // deploys looking unbranded rather than failing.
    const theme = e.theme || DEFAULT_EDITION.theme;
    if (cssDir && theme !== "default" && !fs.existsSync(path.join(cssDir, `theme-${theme}.css`))) {
      throw new Error(
        `lib/editions.js: edition "${e.id}" names theme "${theme}", but ${path.join(cssDir, `theme-${theme}.css`)} does not exist.`
      );
    }
  }
}

module.exports = {
  EDITIONS,
  DEFAULT_EDITION,
  allEditions,
  editionFor,
  editionForDomain,
  getEdition,
  validateEditions
};
