// Canonical registry of per-domain EDITIONS - the copy and flourishes that
// differ between the production domains this one repo deploys to.
//
// "Edition" is the site's own existing word for a per-domain build, not a new
// coinage: src/_includes/excluded.njk has told readers "Not included in this
// edition" since narrowing was introduced. This file makes that concept
// first-class on the authoring side too.
//
// WHY THIS EXISTS, AND WHAT IT IS NOT
//
// Three mechanisms already vary a build per domain, and this is deliberately
// none of them:
//
//   - deploy.conf's CHARACTERS/TOPICS/THREADS (lib/content-filter.js) is
//     SUBTRACTIVE: it narrows an otherwise-full site down to a subset. It can
//     hide a page; it cannot give a domain a sentence of its own.
//   - THEME (src/css/theme-*.css, generated by scripts/generate-themes.js) is
//     COSMETIC: a palette swap, byte-identical to main.css otherwise.
//   - CUSTOM_LORE_FILE / CUSTOM_CSS_FILE (scripts/cpanel-deploy.sh) are
//     ADDITIVE but live OUTSIDE the repo, on the cPanel account. That is the
//     right shape for the case they were built for - content a third-party
//     clone operator owns, which Dermot cannot license into a CC BY-NC-ND
//     repo - and the wrong shape for his own per-domain copy, which wants to
//     be versioned, reviewable, checkable by `npm test` and the link/related
//     scripts, and inside the licence structure CONTENT-LICENSE.md describes.
//
// This registry is the fourth thing: additive, in-repo, per-domain copy.
//
// THE GOVERNING RULE: CANON IS CENTRALISED, VARIANTS ARE NON-CANONICAL
//
// Settled 2026-07-30, and it is a constraint on this file rather than a note
// about it. **Nothing an edition carries may assert a fact about the world.**
// Canon - src/seasons/, src/lore/, src/glossary/ - is identical on every
// domain, and every field here is framing: a tagline, which characters to put
// in a slideshow, which audio to offer. Reword the pitch, never the record.
//
// The test for a proposed field is not "is this nice for that domain?" but
// "could two domains now disagree about something true?" If yes, it does not
// belong here, and it does not belong anywhere else either.
//
// Note that this rule is what makes the multi-domain deployment coherent
// rather than merely convenient. Filtering can only ever SUBTRACT, so a
// narrowed clone shows a subset of one record and never a contradiction of it.
// If an edition could add lore, that guarantee would be gone: two domains
// could describe the same institution differently, and the archive would stop
// being a single record with several doors into it. That is also precisely why
// deploy.conf's CUSTOM_LORE_FILE is deprecated (2026-07-30) - injecting a page
// into src/lore/ per clone was the one mechanism that could produce
// per-domain canon. There is no replacement for it, on purpose.
//
// Two consequences worth stating, since both will come up:
//
//   - A domain that genuinely needs a page of its own gets a NON-canonical
//     one - an "about this edition" note, framing, front-of-house copy - not a
//     lore entry. If the material is worth being true, it is worth being true
//     everywhere, and it belongs in src/lore/ on every domain.
//   - The four canon statuses are unaffected and no fifth is being added.
//     An edition is not canon, not codex (which is in-universe authorship),
//     not an overlay (a declared reading of the same events), and not
//     chartered (another hand's work). It is the shop window, not the archive.
//
// WHY NOT KEEP USING `theme` FOR THIS
//
// Because `theme` was already doing it, and was already at its limit. The
// branches this file replaces were spelled `{% if theme == "fellowship" %}`,
// which conflates palette with identity and fails in three ways as domains
// diverge:
//
//   1. Several domains share one palette. sample-deploy.conf has four `fol*`
//      entries on THEME=fellowship and two `churchspace*` entries on
//      THEME=church-space - six domains, two identities. The moment one of
//      those four wants its own tagline, `theme` cannot express it.
//   2. A domain wanting a general-purpose palette (light, sepia,
//      high-contrast, solarized) plus its own copy had no way to ask: picking
//      the palette silently picked the copy too.
//   3. Copy organised by `theme` lives wherever the template is, so ONE
//      domain's identity scatters across src/index.md, base.njk and anything
//      added later. Edit points grow as domains x templates. This file
//      inverts that: one entry per edition, listing what that edition
//      overrides, however many templates read it.
//
// The two axes are now independent. `EDITION=folspace THEME=fellowship` is a
// sentence you can write.
//
// MIGRATION SAFETY - read before renaming an id
//
// getEdition() falls back to THEME when EDITION is unset, and every id below
// that names an existing look is spelled exactly as that theme is. deploy.conf
// is UNTRACKED and lives on the cPanel account, so the live configs cannot be
// updated from here - a live domain setting only THEME=fellowship therefore
// keeps rendering the fellowship edition with no edit at all. Renaming an id
// below, or dropping the THEME fallback, silently reverts those domains to the
// default copy. Add `EDITION=` to a deploy.conf first; retire the fallback
// only once every live clone sets it.
//
// ADDING AN EDITION
//
// Add an entry with an `id` and only the fields it actually overrides -
// editionFor() merges over DEFAULT_EDITION, so a domain that wants one new
// tagline writes one field, not a full record.
//
// `domains` IS LOAD-BEARING (since 2026-07-30). scripts/resolve-edition.js
// looks a domain up here so scripts/cpanel-deploy.sh can fill in THEME,
// THREADS, CHARACTERS, TOPICS, SITE_NAME, SITE_TITLE, COMMENTS_ENABLED and
// GISCUS_PROFILE for any key that clone's deploy.conf leaves unset - taking a
// minimum viable deploy.conf down to CPANEL_USER and DOMAIN.
//
// **deploy.conf still wins wherever it sets a value** - migration cover, and
// also the right ordering while anything here is unconfirmed.
//
// WHAT IS CONFIRMED, AND WHAT IS NOT (as of 2026-07-30). Be precise about this,
// because a note that says "unconfirmed" long after it was confirmed sends the
// next reader to redo work that is already done:
//
//   - Every `domains` list below is CONFIRMED by Dermot. All twelve domains he
//     manages are accounted for: the ten that resolve here, plus two aliases
//     recorded as a comment further down. The GitHub Pages host on the default
//     edition is not a domain he owns and is correctly listed anyway, since it
//     is a real build target.
//   - The `threads` values are CONFIRMED as of 2026-08-05: Dermot directed
//     that the church-space AND fellowship domain families both focus on the
//     contemplative reading tier, which is carried by the church-space thread
//     - so `threads: ["church-space"]` on both editions, previously inferred
//     from sample-deploy.conf, now stands on his word rather than on an
//     example file.
//   - `theme` follows each edition's own name and is safe on that basis alone.
//
// One correction is worth keeping in view rather than deleting, because it shows
// the failure mode: the fellowship list originally carried "fol.org",
// "folonline" and "folspace", which are ALT_DOMAINS *identifiers* in
// sample-deploy.conf rather than hostnames. Three of four domains resolved as
// unregistered, and any of them omitting THEME would have deployed unbranded.
// The real hostnames were in the same file's ALT_<id>_DOMAIN values, unread.
//
// WHY THIS DOES NOT WEAKEN PRIVATE-THREAD OPT-IN
//
// `threads` below can name `church-space`, a private thread, which
// lib/content-filter.js otherwise hides on every build. That is still explicit
// opt-in by naming, and naming it HERE is stronger than naming it in
// deploy.conf: this file is tracked, reviewed in a pull request, and versioned,
// where an untracked file on a cPanel account is none of those. What must never
// happen is opt-in inferred from the SHAPE of a domain string - "the host
// starts with church-space, so switch the thread on". That is pattern-matching
// masquerading as a decision. A registry entry is a decision.

const fs = require("fs");
const path = require("path");

// Every field an edition may override, with the values the unbranded
// full-site build (fianilchruinne.com, sciencefiction.site, GitHub Pages,
// local dev) uses. Anything absent from an edition below falls back to these.
const DEFAULT_EDITION = {
  id: "default",
  label: "Fian Ilchruinne (canonical full site)",
  // fianilchruinne.com is the CANONICAL address since 2026-08-03 (Dermot's
  // decision; it briefly started life as an alias the same day and was
  // corrected to canonical within the hour). It HOLDS EVERYTHING (Dermot,
  // 2026-08-05): the full record - which still excludes the church-space
  // overlay, because a private thread is opt-in on every build including
  // this one. sciencefiction.site moved to its own general-tier edition
  // entry the same day (see "sciencefiction" below); it had been a served
  // domain of this entry since the registry existed.
  domains: ["fianilchruinne.com", "dermot-r-cochran.github.io/star-rangers"],

  // ---- Deploy configuration, resolved by scripts/resolve-edition.js --------
  // Each of these maps to the deploy.conf key of the same name, upper-cased.
  // All are safe to hold here under the canon rule above: `theme` is a palette,
  // the three filters can only SUBTRACT from one shared record, and the rest
  // are branding or plumbing. None of them can make a domain assert a fact.

  // Palette name; "default" means src/css/main.css as-is.
  theme: "default",

  // The domain in this edition's TIER FAMILY that carries the ranking signal.
  // Empty (the default) means self-canonical: this domain declares itself the
  // canonical home of its own URLs, which is right for a family of one.
  //
  // WHY THIS EXISTS. base.njk's self-canonical is correct where domains truly
  // diverge and wrong where they do not, and until now there was no way to say
  // which. Measured 2026-08-20: two fellowshipoflight domains build
  // byte-identical across all 632 pages, and the fellowship and church-space
  // editions serve the IDENTICAL 62 indexable pages - 62 common, 0 unique to
  // either. Six domains, one page set, six self-canonicals, and Google picking
  // the survivor unaided. That is what this field lets us decide instead.
  //
  // SEMANTICS. It names a HOST, not a page. Any build whose SITE_DOMAIN differs
  // from it emits a cross-domain canonical at the same path; the named host
  // itself compares equal and keeps its self-canonical, so one value can be set
  // once per family and every member reads it correctly. That also means it
  // keeps working unchanged when a family is later split into one edition per
  // specialisation - each entry carries the same ranksAt.
  //
  // THE INVARIANT, and it is load-bearing: **the ranking domain must include
  // every page its siblings include.** A cross-domain canonical pointing at a
  // URL the target build renders as an excluded.njk placeholder would send
  // Google to a noindex page and lose the content altogether. Keeping the
  // ranking domain on the family's widest filter satisfies this by
  // construction; narrow the siblings, never the one that ranks.
  //
  // Consequence elsewhere: a non-ranking domain drops its sitemap entries and
  // its robots.txt Sitemap line (src/sitemap.njk, src/robots.njk). Advertising
  // URLs we have just told Google not to index is contradictory signalling,
  // and Google's own guidance is to keep non-canonical URLs out of sitemaps.
  ranksAt: "",
  // Content narrowing. Empty = no narrowing (the full site). Arrays here,
  // joined to comma-separated strings for the env vars downstream.
  threads: [],
  characters: [],
  topics: [],
  // Branding. Empty = fall back to src/_data/site.js's own defaults.
  siteName: "",
  siteTitle: "",
  // giscus board selected by registered profile name (src/_data/giscus.js).
  // Empty = that file's built-in default profile. The raw GISCUS_*_ID values
  // deliberately do NOT live here: a profile name is meaningful only inside
  // this repo's registry, whereas the raw ids are what an independent host
  // supplies via their own giscus.local.json.
  giscusProfile: "",
  commentsEnabled: true,

  // ---- Copy and flourishes ------------------------------------------------
  // Homepage hero. `heroSubtitle` is trusted HTML - it carries inline links
  // and is rendered through Nunjucks' `safe`, so it is authored content and
  // must never be built from user input.
  heroSubtitle:
    'A station clock is forty seconds wrong, and it has stayed wrong for eleven years.\n    Fian Ilchruinne follows the Star Rangers ordered to measure the drift, guard the public record, and decide what truth still survives across the Five Layers, the <a href="/star-rangers/lore/ensemble-multiverse/">Grand Ensemble Multiverse</a>, and multiple points of view.',

  // Character ids for the hero slideshow, resolved against the (filtered)
  // characters collection by the charactersByIds filter - so an id naming a
  // character this build excludes simply drops out of the slideshow rather
  // than breaking it.
  //
  // That promise is only as good as the CSS honouring it, and for a while it
  // was not: main.css carried crossfade rules for exactly 5 and 6 slides (the
  // two counts listed here), so a narrowed clone that filtered out even one
  // hero character left every remaining slide with no animation and a blank
  // hero - losing the whole image rather than the one character. Fixed in the
  // stylesheet, not here, but worth knowing before adding an edition: the
  // count this list produces on a given domain is whatever survives that
  // domain's CHARACTERS/TOPICS/THREADS, not the length written below.
  heroCharacterIds: ["aldera", "iona", "elvira", "galahad", "rook", "syra"],

  // Footer audio player. `file` is a filename in src/audio/.
  themeAudio: { label: "Celtic ambient", file: "celtic-theme.wav" }
};

// ALIAS DOMAINS - recorded here on purpose, and deliberately NOT in any
// edition's `domains` array (confirmed with Dermot 2026-07-30):
//
//   star-rangers.space      -> sciencefiction.site
//   star-rangers.site       -> starquest.site
//   starquest.online        -> starquest.site      (demoted 2026-08-20)
//   fian-ilchruinne.com     -> fianilchruinne.com
//   fianilchruinne.site     -> fianilchruinne.com
//   fianilchruinne.space    -> fianilchruinne.com
//   fianilchruinne.online   -> fianilchruinne.com
//   fianilchruinne.net      -> fianilchruinne.com
//
// starquest.online is the only one of these that was ever a build. It is here
// under the rule that settled the duplicate-content question on 2026-08-20: a
// REGISTRATION DEFENDS THE NAME, A BUILD HAS TO EARN ITS KEEP. Promote a TLD to
// a build when it has a face of its own to show; until then an alias already
// does the anti-squatting job, and does it better - it cannot become a
// duplicate because it never had its own SITE_DOMAIN to self-canonicalise to.
//
// The five fianilchruinne aliases (added 2026-08-03, same day the .com went
// canonical) are spelling and TLD insurance around the canonical: the
// hyphenated form matches the umbrella's settled spelling Fian-ilchruinne,
// and the .site/.space/.online/.net set closes the obvious typo-TLD space.
// fianilchruinne.ie is NOT registered (not applied for as of 2026-08-03).
//
// These are cPanel aliases: they share their target's document root and serve
// its files, with no Eleventy build of their own. Nothing needs to resolve them,
// and self-canonical already does the right thing without being asked - the HTML
// they serve was built with the TARGET's SITE_DOMAIN, so a page at
// star-rangers.space already carries a canonical naming sciencefiction.site, and
// search engines consolidate to the target on their own.
//
// WHY LISTING THEM UNDER `domains` WOULD BE A TRAP. It would look tidy and would
// do nothing today, because no build asks about them. But `domains` is what
// scripts/resolve-edition.js matches, so the entry would sit there waiting: the
// day one of these was converted to an ALT_DOMAINS entry with its own build, it
// would resolve, build its own copy, and self-canonicalise to ITSELF - turning a
// correctly-consolidated alias into a genuine duplicate competing with the very
// domain it was meant to point at. Recording them as prose says the true thing
// (these hostnames exist and where they go) without arming that.
//
// If one ever does get its own build, the right move is a deliberate one: decide
// then whether it is an edition (give it its own copy, and self-canonical is
// correct) or still an alias (leave it an alias, or 301 it).

// The CONTEMPLATIVE tier's six domains share everything that decides what they
// carry and differ only in how they introduce it. Spread into each entry below
// rather than repeated, so the thread opt-in, the giscus board and the ranking
// host cannot drift apart across six records - which is exactly how the
// fellowship and church-space editions came to serve the identical 62 indexable
// pages without either entry showing it.
//
// WHAT A SPECIALISATION CAN AND CANNOT BE, measured 2026-08-20. It is FRAMING
// ONLY, and that is a property of the filter rather than a lack of ambition:
// lib/content-filter.js unions characters, topics and threads, so a page is in
// if it matches ANY of them. Adding `topics: ["communion-of-the-called"]` on
// top of `threads: ["church-space"]` changes the indexable count by nothing at
// all (62 to 62) because those pages are already inside the thread, and
// dropping the thread to narrow by the tag alone falls to 46 - the shared
// navigational shell, with Season 8 and the private opt-in gone with it.
//
// So there is no way to subdivide one thread by tag today, and each domain's
// own face is its name, its title, its tagline, its palette and its audio.
// That is enough to give a reader arriving at church-space.online a hermitage
// rather than a generic contemplative site, and it is not enough to make the
// page a crawler sees any less of a duplicate - which is why ranksAt exists
// and why all six point at one host. When a house accumulates pages of its own,
// narrow that entry then and relax its canonical.
const CONTEMPLATIVE = {
  threads: ["church-space"],
  giscusProfile: "church-space",
  ranksAt: "fellowshipoflight.org"
};

const EDITIONS = [
  {
    id: "sciencefiction",
    label: "Fian Ilchruinne (general tier)",
    domains: ["sciencefiction.site"],
    // Split out of the default edition 2026-08-05 (Dermot's direction):
    // sciencefiction.site fronts the GENERAL reading tier, while
    // fianilchruinne.com continues to hold everything. "General" is the
    // story bible audience-tier table's tier: founding-era, the tissadelle
    // arc, and any thread not named in that table. THREADS can only name
    // ids, never "everything except X" - so when a new general-tier thread
    // is registered in lib/storyline-threads.js it must ALSO be added here,
    // or it silently won't ship on this domain.
    //
    // NOTE this entry is live-impacting in a way most registry edits are
    // not: this clone historically deployed the full unfiltered site with
    // no THREADS of its own, so if its deploy.conf leaves THREADS unset,
    // the next deploy narrows the live domain to these threads (excluded
    // pages become placeholders pointing at fianilchruinne.com, the
    // full-record reference domain). deploy.conf still wins wherever it
    // sets a value.
    threads: ["founding-era", "tissadelle-arc"]
    // No branding/copy overrides: falls back to the default edition's, so
    // the domain keeps looking exactly as it always has.
  },
  {
    // ---- CONTEMPLATIVE tier, and the domain that ranks for it --------------
    // Restructured 2026-08-20 on Dermot's direction: four families, one per
    // reading tier, each picking one site to rank, with a specialisation per
    // deployment. The fellowship and church-space editions were one family all
    // along - same thread, same giscus board, same 62 pages - so they are six
    // entries of one family here rather than two records that looked unrelated.
    //
    // This entry is the one that RANKS, so it carries the family's widest
    // filter and its most general face: the Fellowship entire, both chapters of
    // it. That is not a stylistic choice. The invariant on ranksAt is that the
    // ranking domain must include every page its siblings include, or a
    // sibling's canonical points at a noindex placeholder and the page is lost.
    // Leaving this entry unnarrowed satisfies that by construction.
    //
    // WHY THERE ARE THREE HOUSES BELOW AND NOT FOUR. The instruction was four
    // chapter houses for four domains, and canon supplies three: the Eden
    // chapter house (named), Brother Daire's abbey on a tidal river (unnamed),
    // and Asteria's house on a green hill (unnamed). There is no fourth, and
    // Cnoc na mBeach cannot be pressed into service as one - its own entry says
    // it is "not a monastery in any sense the Fellowship of Light or the
    // Monasteries of Mars would recognize as their own". Putting the whole
    // Fellowship on the ranking domain and the three real houses on the three
    // siblings needs no fourth to be invented, which is the better answer for
    // the same reason the record declines to fix a date it does not have.
    id: "fellowship",
    label: "Fellowship of Light (the order entire)",
    domains: ["fellowshipoflight.org"],
    theme: "fellowship",
    ...CONTEMPLATIVE,
    // Per-edition branding (2026-08-03): SITE_NAME drives the header logo,
    // footer and the homepage <h1> (src/index.md); SITE_TITLE the browser
    // tab. deploy.conf still wins wherever the live clone sets either.
    siteName: "Fellowship of Light",
    siteTitle: "Fellowship of Light",
    heroSubtitle:
      'A station clock is forty seconds wrong, and it has stayed wrong for eleven years. Long before any charter named them Rangers, an older order kept vigil at boundaries like this one. Fian Ilchruinne follows the people who inherited that watch — measuring the drift, guarding the public record, and deciding what light still survives across the Five Layers, multiple <a href="/star-rangers/glossary/concordant/">Concordants</a>, and multiple points of view.',
    themeAudio: { label: "Orchestral fantasy", file: "fellowship-theme.wav" }
  },
  {
    // Chapter house 1 of 3, and the only one canon has named. It holds the
    // cross-chapter correspondence and the comparative archive's filing - the
    // one house whose work is explicitly the comparing of accounts, which is
    // also the tier's best door into the series' own subject.
    id: "fellowship-eden",
    label: "Fellowship of Light — the Eden chapter house",
    domains: ["fellowshipoflight.site"],
    theme: "fellowship",
    ...CONTEMPLATIVE,
    siteName: "The Eden Chapter House",
    siteTitle: "The Eden Chapter House — Fellowship of Light",
    heroSubtitle:
      'A station clock is forty seconds wrong, and it has stayed wrong for eleven years. The house that keeps the correspondence has seen the shape before: independent accounts of one thing, arriving from chapters that never spoke to each other, filed under <a href="/star-rangers/lore/arilon/">Arilon</a> because no single tradition can be credited with them. Fian Ilchruinne read from the archive that compares them.',
    themeAudio: { label: "Orchestral fantasy", file: "fellowship-theme.wav" }
  },
  {
    // Chapter house 2 of 3. Canon and unnamed - Brother Daire's house, where
    // Elvira was taught years before the Marsh Causeway (S01E00C01, The Garden
    // Gate). Fronted by description rather than a name on purpose: naming it is
    // a one-way door and belongs to a scene that needs the name spoken, not to
    // a domain that wants a title.
    id: "fellowship-abbey",
    label: "Fellowship of Light — the abbey on the tidal river",
    domains: ["fellowshipoflight.online"],
    theme: "fellowship",
    ...CONTEMPLATIVE,
    siteName: "The Abbey on the Tidal River",
    siteTitle: "The Abbey on the Tidal River — Fellowship of Light",
    heroSubtitle:
      'A station clock is forty seconds wrong, and it has stayed wrong for eleven years. An abbey on a tidal river taught people to notice that kind of thing centuries before an instrument could measure it, and still calls it the <a href="/star-rangers/glossary/overfold/">Overfold</a> — not out of superstition, but because whoever coined the word was right about something real. Fian Ilchruinne from the house that teaches the noticing.',
    themeAudio: { label: "Orchestral fantasy", file: "fellowship-theme.wav" }
  },
  {
    // Chapter house 3 of 3. Canon and unnamed - the stone house on a green hill
    // with a track running past it, where Asteria went as a Sage at about a
    // hundred. Its lens is the one the Corps cannot supply: an institution that
    // asks nothing about what she commanded.
    id: "fellowship-green-hill",
    label: "Fellowship of Light — the house on the green hill",
    domains: ["fellowshipoflight.space"],
    theme: "fellowship",
    ...CONTEMPLATIVE,
    siteName: "The House on the Green Hill",
    siteTitle: "The House on the Green Hill — Fellowship of Light",
    heroSubtitle:
      'A station clock is forty seconds wrong, and it has stayed wrong for eleven years. A stone house on a green hill, a track running past it, and inside it people who gave up every interest the argument outside is about — which is the one qualification a service record cannot supply and cannot compromise either. Fian Ilchruinne read from the far side of a career.',
    themeAudio: { label: "Orchestral fantasy", file: "fellowship-theme.wav" }
  },
  {
    id: "starquest",
    label: "StarQuest",
    // starquest.online was the second domain here until 2026-08-20, when it was
    // demoted to a cPanel alias of starquest.site and moved to the alias list
    // above. It had a build of its own and nothing of its own to put in it: the
    // orbital-five-o thread is ONE task force (the Governor's Investigative
    // Task Force) and Season 4 is ONE chapter, so there was no second face to
    // give it. An alias serves the same pages, consolidates on its own, and
    // costs no build. A family of one needs no ranksAt.
    domains: ["starquest.site"],
    theme: "starquest",
    // "Orbital Five-O" (2026-08-03): the StarQuest domains' own brand. The
    // exact phrase was vetted unowned; the Hawaii Five-0 echo is deliberate.
    // The edition id and theme stay "starquest" - see MIGRATION SAFETY above.
    siteName: "Orbital Five-O",
    siteTitle: "Orbital Five-O",
    // These domains front the orbital-five-o storyline thread AND the YOUNG
    // ADULT reading tier (2026-08-05, Dermot's direction; the story bible's
    // audience-tier table maps the two to each other) - the same shape as the
    // pets entry's topics above:
    // recorded in the registry so a clone trimmed to the two-key deploy.conf
    // keeps the narrowing, and reviewable here rather than living only on a
    // server. Thread membership does the matching (Season 2 chapters via
    // lib/storyline-threads.js, everything else via the orbital-five-o tag),
    // so the filter and the content cannot drift apart. deploy.conf still
    // wins wherever it sets THREADS - nothing changes for a live clone until
    // its own line is removed there.
    threads: ["orbital-five-o"],
    heroSubtitle:
      'Forty seconds of drift. Eleven years unexplained. At the edge of the known, that\'s not a rounding error — it\'s a warning. Fian Ilchruinne follows the crews sent to chase it down: measuring the boundary, guarding the record, and racing to decide what\'s true before the Five Layers, the <a href="/star-rangers/glossary/concordant/">Concordants</a>, and every conflicting witness bury the answer for good.',
    themeAudio: { label: "Sci-fi ambient", file: "starquest-theme.wav" }
  },
  {
    id: "pets",
    label: "Undercover Pets",
    domains: ["undercover-pets.com"],
    theme: "pets",
    // The narrowing this domain has always deployed with, recorded here so a
    // clone that trims deploy.conf to the two-key minimum keeps it. Left unset,
    // the registry supplied no topics at all and the domain would have silently
    // served the full unfiltered site - the failure mode is quiet and in the
    // permissive direction, which is the worse one to leave to a default.
    //
    // The tag is the domain name on purpose: `undercover-pets.com` is what
    // pages carry to opt INTO this deploy (agent-barsik.md, bubochka.md,
    // smart-pet.md and two dozen others), so the filter and the tag cannot
    // drift apart the way a curated character list would. deploy.conf still
    // wins wherever it sets TOPICS, so this changes nothing for the live clone
    // until someone removes that line there.
    topics: ["undercover-pets.com"],
    // Season 2 belongs to the undercover-pets storyline thread (2026-08-05,
    // Dermot's call - see lib/storyline-threads.js). Naming the thread here
    // pulls its chapters in by SEASON membership, so a future Season 2
    // chapter that forgets the undercover-pets.com tag still ships on this
    // domain rather than silently dropping out of it.
    threads: ["undercover-pets"],
    siteName: "Undercover Pets Detective Agency",
    siteTitle: "Undercover Pets Detective Agency",
    heroSubtitle:
      'A station clock is forty seconds wrong, and it has stayed wrong for eleven years — a small enough error that everyone assumed someone else was watching it. Fian Ilchruinne follows the people who finally did: measuring the drift, guarding the public record, and working out what truth still holds across the Five Layers, multiple <a href="/star-rangers/glossary/concordant/">Concordants</a>, and multiple points of view.',
    // The one existing edition that recasts the hero slideshow rather than
    // only rewording around it.
    heroCharacterIds: ["barsik", "bubochka", "eden-warden", "nessa", "rasa-oyelaran"],
    themeAudio: { label: "Playful ukulele", file: "pets-theme.wav" }
  },
  {
    // ---- The two church-space domains, same family -------------------------
    // No COPY overrides until 2026-08-20: these domains diverged through the
    // private thread and their palette rather than through reworded
    // front-of-house text. They have faces now, and both are institutions canon
    // already carries - neither of which is a Fellowship house, which is the
    // point. The tier holds three distinct orders and this is two of them.
    id: "church-space",
    label: "Church Space — the Communion of the Called",
    domains: ["church-space.site"],
    theme: "church-space",
    ...CONTEMPLATIVE,
    siteName: "The Communion of the Called",
    siteTitle: "The Communion of the Called",
    heroSubtitle:
      'A station clock is forty seconds wrong, and it has stayed wrong for eleven years. The <a href="/star-rangers/lore/communion-of-the-called/">Communion</a> keeps no charter and elects nobody, and a High Captain and a Cadet sit in the same station chapel on the same footing, because its only qualification for belonging is showing up. Fian Ilchruinne read on a Ranger\'s own time.',
    // Added 2026-08-20 (Dermot's direction: "Rotational Hum is site
    // furniture", church-space chosen as the slot). Until now this edition
    // registered no audio and fell through to the default's Celtic ambient -
    // which was never a decision, just the absence of one.
    //
    // Two departures from the four existing themes, both deliberate:
    //   - m4a rather than wav. The others are 4-8 MB uncompressed for a
    //     decorative footer element; this is the same audio at a third of the
    //     bytes. New audio should follow it (story-bible/music-prompts.md).
    //   - It runs 4:02 and it builds, where a theme loop is meant to stay flat
    //     and go nowhere. That is survivable because base.njk sets
    //     preload="none" and gives the reader a play button rather than
    //     autoplaying: nobody hears it who did not ask to. The `loop`
    //     attribute will restart it audibly if anyone plays it to the end -
    //     accepted, and the fix if it ever grates is a trimmed 90 s cut, not a
    //     different track.
    themeAudio: { label: "Ambient drone", file: "rotational-hum.m4a" }
  },
  {
    // The smallest unit the Communion has ever produced: one keeper, a
    // hive-yard, a standing door. The only contemplative domain whose hero cast
    // can be set meaningfully - Brother Fintan is the single character page a
    // contemplative build renders as real content rather than a placeholder.
    id: "church-space-cnoc",
    label: "Church Space — Cnoc na mBeach",
    domains: ["church-space.online"],
    theme: "church-space",
    ...CONTEMPLATIVE,
    siteName: "Cnoc na mBeach",
    siteTitle: "Cnoc na mBeach — the hill of the bees",
    heroSubtitle:
      'A station clock is forty seconds wrong, and it has stayed wrong for eleven years. At <a href="/star-rangers/lore/cnoc-na-mbeach/">Cnoc na mBeach</a> a hive is told of a death, a birth or a departure, on reasoning older than any instrument the Safety Corps ever certified — and nobody there claims it does anything a reading would confirm. Mark what is confirmed, mark what is kept out of habit, and never blur the two. Fian Ilchruinne from the hill of the bees.',
    heroCharacterIds: ["brother-fintan"],
    themeAudio: { label: "Ambient drone", file: "rotational-hum.m4a" }
  }
];

// An untracked, gitignored editions.local.json in the repo root, for anyone
// hosting this site independently. Exactly the pattern giscus.local.json
// already establishes (see src/_data/giscus.js), and for the same reason:
// registering your own domain should not require editing a tracked engine file,
// because that means maintaining a fork and re-resolving a conflict on every
// upstream merge. Template: sample-editions.local.json.
//
// Shape: { "editions": [ { "id": "...", "domains": [...], ...overrides } ] }
//
// An entry whose id matches one below OVERRIDES it (merged over, field by
// field); a new id is added. So an independent host can either re-point an
// existing edition at their own domain or declare their own outright.
//
// The canon rule still binds a local file completely - there is no field here
// that can add lore, and that is deliberate. It means an independent host
// cannot publish their own material as this story's canon even by accident,
// which protects them as much as it protects the record.
const LOCAL_CONFIG_PATH = path.join(__dirname, "..", "editions.local.json");

let localCache; // undefined = not yet read, null = absent

function loadLocalEditions() {
  if (localCache !== undefined) return localCache;

  let raw;
  try {
    raw = fs.readFileSync(LOCAL_CONFIG_PATH, "utf8");
  } catch (err) {
    if (err.code === "ENOENT") { localCache = null; return localCache; }
    throw err;
  }

  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    throw new Error(`lib/editions.js: editions.local.json is not valid JSON - ${err.message}`);
  }
  const list = parsed && parsed.editions;
  if (!Array.isArray(list)) {
    throw new Error(
      "lib/editions.js: editions.local.json must be { \"editions\": [ ... ] }. " +
      "See sample-editions.local.json for the expected shape."
    );
  }
  for (const e of list) {
    if (!e || typeof e.id !== "string" || !e.id.trim()) {
      throw new Error("lib/editions.js: every entry in editions.local.json needs a non-empty string `id`.");
    }
  }
  localCache = list;
  return localCache;
}

/**
 * The tracked registry with any editions.local.json entries merged in.
 * @returns {object[]} edition records (not yet merged over DEFAULT_EDITION)
 */
function allEditions() {
  const local = loadLocalEditions();
  if (!local || !local.length) return EDITIONS;

  const byId = new Map(EDITIONS.map((e) => [e.id, e]));
  for (const entry of local) {
    const id = entry.id.trim().toLowerCase();
    byId.set(id, { ...(byId.get(id) || {}), ...entry, id });
  }
  return [...byId.values()];
}

/**
 * Merge an edition over DEFAULT_EDITION so callers always get a complete
 * record and an entry only has to declare what it changes. Shallow by design:
 * `themeAudio` is replaced wholesale rather than merged key-by-key, because a
 * half-overridden audio player (new label, old file) is never what anyone
 * means.
 *
 * @param {string} id
 * @returns {object} complete edition record; DEFAULT_EDITION for an unknown id
 */
function editionFor(id) {
  const wanted = String(id || "").trim().toLowerCase();
  const found = allEditions().find((e) => e.id === wanted);
  return found ? { ...DEFAULT_EDITION, ...found } : { ...DEFAULT_EDITION };
}

/**
 * Look an edition up by the domain it serves.
 *
 * Matching is on the bare host, case-insensitively, with any scheme, `www.`,
 * port, path and trailing slash stripped first - so "https://Church-Space.site/"
 * and "church-space.site" are the same domain. A path-bearing entry (the
 * GitHub Pages one, "dermot-r-cochran.github.io/star-rangers") is matched on
 * its host part too, since a host cannot serve two editions.
 *
 * Returns null rather than DEFAULT_EDITION on no match, so a caller can tell
 * "this domain is registered as the default edition" apart from "this domain is
 * not registered at all" - the deploy log says which, and a silent default is
 * how a domain ends up quietly serving the wrong thing.
 *
 * @param {string} domain
 * @returns {object|null} complete edition record, or null if unregistered
 */
function editionForDomain(domain) {
  const host = bareHost(domain);
  if (!host) return null;
  const all = [DEFAULT_EDITION, ...allEditions()];
  const found = all.find((e) => (e.domains || []).some((d) => bareHost(d) === host));
  return found ? { ...DEFAULT_EDITION, ...found } : null;
}

function bareHost(value) {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/^[a-z]+:\/\//, "")
    .replace(/^www\./, "")
    .split("/")[0]
    .split(":")[0];
}

/**
 * Resolve the edition for this build from the environment.
 *
 * EDITION wins; THEME is the migration fallback (see MIGRATION SAFETY above);
 * an unset or unrecognised value yields DEFAULT_EDITION. Deliberately does NOT
 * throw on an unknown id, unlike GISCUS_PROFILE in src/_data/giscus.js - a
 * wrong giscus profile silently attaches reader comments to the wrong repo,
 * which is unrecoverable, whereas a wrong edition id costs a domain its
 * tagline and is obvious on the homepage.
 *
 * @returns {object} complete edition record
 */
function getEdition() {
  return editionFor(process.env.EDITION || process.env.THEME);
}

/**
 * Fail the build on a malformed registry. Called from .eleventy.js at config
 * time, so a mistake here stops the build instead of shipping a broken page.
 *
 * This exists because moving copy out of src/ cost some automatic checking,
 * and the loss should be paid back rather than absorbed. Two specifics:
 *
 *   - `themeAudio.file` used to appear in base.njk as a literal audio src
 *     under /star-rangers/audio/, which scripts/check-internal-links.js
 *     verified. It is now a bare filename assembled by a template, so that
 *     script skips it as a templated href - a typo would ship a player
 *     pointing at nothing. Checked against src/audio/ here instead.
 *     (Deliberately described rather than quoted as a path: that script now
 *     scans this file, and a made-up example URL in a comment would fail it -
 *     as one did while this was being written.)
 *   - `heroSubtitle` links ARE still covered: check-internal-links.js now
 *     scans this file by name (see its EXTRA_FILES).
 *
 * Duplicate ids are checked too: EDITIONS_BY_ID would silently keep the last
 * one, the same quiet-wrong-answer failure validate-content.js guards against
 * for chapter comment_id collisions.
 *
 * @param {string} audioDir absolute path to the directory holding audio files
 * @throws {Error} on a duplicate id, or an audio file that isn't there
 */
function validateEditions({ audioDir, cssDir }) {
  const all = [DEFAULT_EDITION, ...allEditions()];

  const seenIds = new Set();
  for (const e of all) {
    if (seenIds.has(e.id)) {
      throw new Error(`lib/editions.js: duplicate edition id "${e.id}" - only one of them would ever be used.`);
    }
    seenIds.add(e.id);
  }

  // A domain claimed by two editions is the worst failure mode this file has:
  // resolution would pick whichever came first and the other domain would
  // quietly serve the wrong branding forever. Cheap to rule out here.
  const seenDomains = new Map();
  for (const e of all) {
    for (const d of e.domains || []) {
      const host = bareHost(d);
      if (seenDomains.has(host)) {
        throw new Error(
          `lib/editions.js: domain "${host}" is claimed by both "${seenDomains.get(host)}" and "${e.id}".`
        );
      }
      seenDomains.set(host, e.id);
    }
  }

  // A ranksAt naming a host no edition serves is a total, silent failure: every
  // page on every sibling would canonical to a URL nothing builds, and the
  // family's whole content would drop out of the index while the deploy logs
  // success. The typo and the deleted-entry cases both land here.
  for (const e of all) {
    if (!e.ranksAt) continue;
    const host = bareHost(e.ranksAt);
    if (!seenDomains.has(host)) {
      throw new Error(
        `lib/editions.js: edition "${e.id}" has ranksAt "${host}", which no edition claims in its domains. ` +
        `Every page on this domain would canonical to a host nothing builds.`
      );
    }
    // The invariant behind ranksAt: the ranking domain must include every page
    // its siblings include, or a canonical points at a noindex placeholder and
    // the page is lost. Can't be fully checked without building both, but the
    // filters being a SUPERSET is necessary, and the common way to break it is
    // narrowing the ranking domain rather than the siblings.
    const target = all.find((x) => (x.domains || []).some((d) => bareHost(d) === host));
    if (target && target !== e) {
      for (const key of ["threads", "characters", "topics"]) {
        const mine = e[key] || [];
        const theirs = target[key] || [];
        // An empty list on the target means "no narrowing on this axis", which
        // is always a superset. Otherwise every value the sibling carries has
        // to be carried by the ranking domain too.
        if (!theirs.length) continue;
        const missing = mine.filter((v) => !theirs.includes(v));
        if (missing.length) {
          throw new Error(
            `lib/editions.js: edition "${e.id}" ranks at "${host}" but carries ${key} ` +
            `[${missing.join(", ")}] that "${target.id}" does not. The ranking domain must be a superset - ` +
            `narrow the siblings, never the one that ranks.`
          );
        }
      }
    }
  }

  for (const e of all) {
    const file = (e.themeAudio || DEFAULT_EDITION.themeAudio).file;
    if (!fs.existsSync(path.join(audioDir, file))) {
      throw new Error(
        `lib/editions.js: edition "${e.id}" names themeAudio.file "${file}", which is not in ${audioDir}.`
      );
    }
    // A typo'd theme name is not otherwise loud: cpanel-deploy.sh checks the
    // file exists and silently keeps main.css when it doesn't, so the domain
    // deploys looking unbranded rather than failing.
    const theme = e.theme || DEFAULT_EDITION.theme;
    if (cssDir && theme !== "default" && !fs.existsSync(path.join(cssDir, `theme-${theme}.css`))) {
      throw new Error(
        `lib/editions.js: edition "${e.id}" names theme "${theme}", but ${path.join(cssDir, `theme-${theme}.css`)} does not exist.`
      );
    }
  }
}

module.exports = {
  EDITIONS,
  DEFAULT_EDITION,
  allEditions,
  editionFor,
  editionForDomain,
  getEdition,
  validateEditions
};
